sonar.projectKey=siddhikhomane-ui_job-board-devops
sonar.organization=siddhikhomane-ui

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/node_modules/**

# Correct Python version (not 3)
sonar.python.version=3.11